server:
  port: 8082

spring:
  application:
    name: history-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/glucovision-history-db

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10  # Envoie un heartbeat toutes les 10 secondes
    lease-expiration-duration-in-seconds: 30  # Supprime l'instance si aucun heartbeat pendant 30s
