
services:
  # ======================== FRONTEND ========================
  frontend:
    build: ./front
    ports:
      - "4200:80"
    depends_on:
      - gateway-service

  # ======================== BACKEND =========================
  gateway-service:
    build: ./back/gateway-service
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs 
    depends_on:
      - auth-service
      - patient-service
      - note-service
      - diabetes-risk-service
    environment:
      JWT_SECRET: 2baf4d3b0e9b42c68fe6d9e9bdcdfcbf2baf4d3b0e9b42c68fe6d9e9bdcdfcbf
      INTERNAL_API_KEY: GLUCOVISION-INTERNAL-KEY-9b7e85f1-74ac-4b34-8f13-270b3fd6e1d7

  auth-service:
    build: ./back/auth-service
    ports:
      - "8088:8080"
    volumes:
      - ./logs:/app/logs 
    depends_on:
      - mysql-auth
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-auth:3306/glucovision-auth-db?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootroot
      JWT_SECRET: 2baf4d3b0e9b42c68fe6d9e9bdcdfcbf2baf4d3b0e9b42c68fe6d9e9bdcdfcbf
      INTERNAL_API_KEY: GLUCOVISION-INTERNAL-KEY-9b7e85f1-74ac-4b34-8f13-270b3fd6e1d7
      
  patient-service:
    build: ./back/patient-service
    ports:
      - "8085:8080"
    volumes:
      - ./logs:/app/logs    
    depends_on:
      - mysql-patient
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-patient:3306/glucovision-patient-db?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootroot
      JWT_SECRET: 2baf4d3b0e9b42c68fe6d9e9bdcdfcbf2baf4d3b0e9b42c68fe6d9e9bdcdfcbf
      INTERNAL_API_KEY: GLUCOVISION-INTERNAL-KEY-9b7e85f1-74ac-4b34-8f13-270b3fd6e1d7



  note-service:
    build: ./back/note-service
    ports:
      - "8086:8080"
    volumes:
      - ./logs:/app/logs 
    depends_on:
      - mongodb-note
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb-note:27017/glucovision-note-db
      JWT_SECRET: 2baf4d3b0e9b42c68fe6d9e9bdcdfcbf2baf4d3b0e9b42c68fe6d9e9bdcdfcbf
      INTERNAL_API_KEY: GLUCOVISION-INTERNAL-KEY-9b7e85f1-74ac-4b34-8f13-270b3fd6e1d7

  diabetes-risk-service:
    build: ./back/diabetes-risk-service
    ports:
      - "8087:8080"
    volumes:
      - ./logs:/app/logs 
    depends_on:
      - note-service
      - patient-service
    environment:
      JWT_SECRET: 2baf4d3b0e9b42c68fe6d9e9bdcdfcbf2baf4d3b0e9b42c68fe6d9e9bdcdfcbf
      INTERNAL_API_KEY: GLUCOVISION-INTERNAL-KEY-9b7e85f1-74ac-4b34-8f13-270b3fd6e1d7

  # ======================== DATABASES =========================
  mysql-auth:
    image: mysql:8.0.36
    volumes:
      - mysql-auth-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./back/auth-service/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: glucovision-auth-db
  mysql-patient:
    image: mysql:8.0.36
    volumes:
      - mysql-patient-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./back/patient-service/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: glucovision-patient-db

  mongodb-note:
    image: mongo:6.0
    volumes:
      - mongodb-note-data:/data/db
      - ./back\note-service\mongo-init:/docker-entrypoint-initdb.d:ro
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: glucovision-note-db

   # === LOGGING STACK ===
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./logs:/var/log/myapp
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"


volumes:
  mysql-auth-data:
  mysql-patient-data:
  mongodb-note-data:

