spring:
  application:
    name: note-service

spring.config.import: "optional:configserver:http://localhost:8888/"
#logging:
#  level:
  #  root: DEBUG  # Active les logs pour voir s’il récupère la config
