server:
  port: 8080

spring:
  application:
    name: note-service

internal:
  api:
    key: GLUCOVISION-INTERNAL-KEY-9b7e85f1-74ac-4b34-8f13-270b3fd6e1d7

patient-service:
  url: http://patient-service:8080

auth-service:
  url: http://auth-service:8080

