server:
  port: 8082

spring:
  application:
    name: note-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/glucovision-history-db

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG


