server:
  port: 8080

spring:
  application:
    name: note-service

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/testdb}

internal:
  api:
    key: ${INTERNAL_API_KEY}  # Or ${INTERNAL_API_KEY:default-key} if you want a fallback value

jwt:
  secret: ${JWT_SECRET}  # Secret key for JWT token validation (injected from environment variable)

patient-service:
  url: http://patient-service:8080

auth-service:
  url: http://auth-service:8080

management:
  endpoints:
    web:
      exposure:
        include: health, info

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

# Custom API metadata
info:
  title: GlucoVision API
  version: v1
  description: API for managing medical notes.
