server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/Users/fouad/Documents/openclassroom/P9/back/glucovision-config
