package com.glucovision.noteservice.model;


import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;


import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.util.UUID;
/**
 * Represents a medical note stored in the MongoDB "note" collection.
 * <p>
 * Each note is associated with a specific patient and contains:
 * <ul>
 *     <li>A comment describing the patient's condition or observation</li>
 *     <li>A timestamp for when the note was created</li>
 *     <li>An optional modification timestamp</li>
 * </ul>
 */
@Data
@Document(collection = "note")
public class Note {

    /**
     * Default constructor for framework usage.
     */
    public Note() {
    }

    /**
     * Constructor used when creating a new note.
     *
     * @param patientId    the ID of the patient linked to the note
     * @param comments     the content of the note
     * @param creationDate the timestamp when the note was created
     */
    public Note(String patientId, String comments, LocalDateTime creationDate) {
        this.patientId = patientId;
        this.comments = comments;
        this.creationDate = creationDate;
    }

    /**
     * Unique identifier for the note, automatically generated by MongoDB.
     */
    @Id
    private String id;

    /**
     * The ID of the patient associated with this note.
     */
    private String patientId;

    /**
     * Content of the medical note.
     */
    private String comments;

    /**
     * Timestamp when the note was created.
     */
    private LocalDateTime creationDate;

    /**
     * Timestamp when the note was last modified, if applicable.
     */
    private LocalDateTime modificationDate;
}
