server:
  port: 8080

spring:
  application:
    name: gateway-service

  main:
    web-application-type: reactive  # ✅ Important pour WebFlux
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration  # ✅ Désactive Spring Security

  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: patient-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
