server:
  port: 8080

spring:
  application:
    name: gateway-service

  main:
    web-application-type: reactive  # ✅ Requis pour Spring Cloud Gateway (WebFlux)

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration


jwt:
  secret: ${JWT_SECRET}  # Secret key for JWT token validation (injected from environment variable)


management:
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  file:
    name: /app/logs/gateway-service.log
  level:
    root: INFO