server:
  port: 8084

spring:
  application:
    name: diabetes-risk-service

patient-service:
  url: http://localhost:8085

note-service:
  url: http://localhost:8082

internal:
  api:
    key: GLUCOVISION-INTERNAL-KEY-9b7e85f1-74ac-4b34-8f13-270b3fd6e1d7
