server:
  port: 8761  # Port standard pour Eureka

spring:
  application:
    name: eureka-server

eureka:
  server:
    enable-self-preservation: false   # Désactive le mode "self-preservation" pour éviter l'alerte
    eviction-interval-timer-in-ms: 30000  # Vérifie les instances toutes les 30s (au lieu de 60s)
  client:
    register-with-eureka: false  # Le serveur ne s'enregistre pas lui-même
    fetch-registry: false  # Il ne récupère pas la liste des services (il est le registre)
