server:
  port: 8080

spring:
  application:
    name: patient-service
  jackson:
    mapper:
      accept-case-insensitive-enums: true  # Allows case-insensitive enum values in JSON (e.g., "male", "MALE", etc.)

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate  # Validate the schema against entity mappings at startup
    show-sql: true        # Display SQL queries in the console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: ${JWT_SECRET}  # Secret key for JWT token validation (injected from environment variable)

management:
  endpoints:
    web:
      exposure:
        include: health, info  # Exposes actuator endpoints for health and info

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

# Custom API metadata
info:
  title: GlucoVision API
  version: v1
  description: API for managing patients.
